#!/usr/bin/env python3
"""Plot per-frame loss rate from WebRTC receiver CSV output.

Reads /tmp/frame_loss.csv (generated by FrameLossTracker) and produces
two plots:
  1. Instantaneous frame loss rate vs frame number
  2. Cumulative frame loss rate vs frame number

Run: python3 plot_loss.py [csv_file]
"""

import sys
import csv
import matplotlib.pyplot as plt


def main():
    csv_path = sys.argv[1] if len(sys.argv) > 1 else "/tmp/frame_loss.csv"

    frame_numbers = []
    loss_rates = []
    cumulative_rates = []
    widths = []
    skipped = []

    with open(csv_path, "r") as f:
        reader = csv.DictReader(f)
        for row in reader:
            frame_numbers.append(int(row["frame_number"]))
            loss_rates.append(float(row["loss_rate"]))
            cumulative_rates.append(float(row["cumulative_loss_rate"]))
            widths.append(int(row["width"]))
            skipped.append(int(row["skipped_frames"]))

    if not frame_numbers:
        print(f"No data in {csv_path}")
        return

    total_skipped = sum(skipped)
    total_received = len(frame_numbers)
    total_expected = total_received + total_skipped
    avg_loss = total_skipped / total_expected * 100 if total_expected > 0 else 0

    print(f"Total received:  {total_received}")
    print(f"Total skipped:   {total_skipped}")
    print(f"Total expected:  {total_expected}")
    print(f"Average loss:    {avg_loss:.1f}%")
    print(f"Final cumulative loss: {cumulative_rates[-1]*100:.1f}%")

    fig, (ax1, ax2) = plt.subplots(2, 1, figsize=(14, 8), sharex=True)

    # Plot 1: Instantaneous loss rate.
    ax1.plot(frame_numbers, loss_rates, "r.", markersize=4, alpha=0.7, label="Per-frame loss")
    # Highlight frames where packets were actually skipped.
    skipped_frames = [f for f, s in zip(frame_numbers, skipped) if s > 0]
    skipped_rates = [r for r, s in zip(loss_rates, skipped) if s > 0]
    if skipped_frames:
        ax1.plot(skipped_frames, skipped_rates, "ro", markersize=6, alpha=0.9, label="Frame skipped")
    ax1.set_ylabel("Instantaneous Loss Rate")
    ax1.set_ylim(-0.05, 1.05)
    ax1.legend(loc="upper right")
    ax1.grid(True, alpha=0.3)
    ax1.set_title(f"WebRTC Frame Loss: {total_received} received, {total_skipped} skipped ({avg_loss:.1f}%)")

    # Plot 2: Cumulative loss rate.
    ax2.plot(frame_numbers, cumulative_rates, "b-", linewidth=1.5, label="Cumulative loss rate")
    ax2.axhline(y=avg_loss / 100, color="r", linestyle="--", alpha=0.7, label=f"Average: {avg_loss:.1f}%")
    ax2.set_ylabel("Cumulative Loss Rate")
    ax2.set_ylim(-0.01, max(cumulative_rates) * 1.2 + 0.05)
    ax2.legend(loc="upper right")
    ax2.grid(True, alpha=0.3)
    ax2.set_xlabel("Frame Number")

    # Color-code resolution changes on both plots.
    prev_w = widths[0]
    for i, w in enumerate(widths):
        if w != prev_w:
            ax1.axvline(x=i, color="gray", linestyle=":", alpha=0.5)
            ax2.axvline(x=i, color="gray", linestyle=":", alpha=0.5)
            prev_w = w

    plt.tight_layout()
    output_path = "/tmp/frame_loss.png"
    plt.savefig(output_path, dpi=150)
    print(f"\nSaved plot to {output_path}")
    plt.close()


if __name__ == "__main__":
    main()
